---
# handlers file for ansible-role-update-repository
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true
  become: true

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
